backend:
  name: github
  repo: larsbehrenberg/impressionistarts.larsbehrenberg.com

media_folder: /static/assets/
public_folder: /assets/

collections:
  - name: "posts"
    label: "Posts"
    folder: "/content/posts/"
    create: true
    fields:
      - { name: "path", label: "Slug" }
      - { name: "date", label: "Published Date", widget: "datetime" }
      - { name: "title", label: "Title" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "tags", label: "Tags", widget: "list" }
      - { name: "cover", label: "Featured Image", widget: "image", required: true }
      - label: "Text sections"
        name: "textSections"
        widget: "list"
        allow_add: true
        collapsed: false
        fields:
          - {label: Text Title, name: textTitle, widget: string, default: "This is the text title!"}
          - {label: Text, name: text, widget: string, default: "This is the body text!"}
          - label: "Gallery"
            name: "galleryImages"
            widget: "list"
            collapsed: false
            allow_add: false
            field: {label: Image 1, name: image1, widget: image}
  
  - name: "maps"
    label: "Maps"
    folder: "/content/maps/"
    create: true
    fields:
      - { name: "path", label: "Path" }
      - { name: "title", label: "Title" }
      - { name: "googleApi", label: "Google API URL"}
      - { name: "tags", label: "Tags", widget: "list" }