backend:
  name: github
  repo: larsbehrenberg/impressionistarts.larsbehrenberg.com

media_folder: /content/posts
public_folder: /content

collections:
  - name: "posts"
    label: "Posts"
    folder: "/content/posts"
    create: true
    fields:
      - { name: "path", label: "Path" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "title", label: "Title" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "tags", label: "Tags", widget: "list" }
      - { name: "cover", label: "Featured Image", widget: "image", required: true}